# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
#Type your code here
import joblib
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from skopt import BayesSearchCV
from sklearn.pipeline import Pipeline
from skopt.space import Real, Categorical
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced] -> untuk yang ini bagaimana ya? di cell file clustering diminta untuk mengintegrasi hasil dari inverse sedangkan hasil dari inverse adalah kategori
# asalnya dimana bukan bentuk numerik dan juga dan disini tidak di perbolehkan mengubah template untuk tahapan data preparation.
# Lengkapi kode berikut
# ___ = pd_read_csv("___.csv")
df = pd.read_csv("data_clustering_inverse.csv")

In [3]:
# Tampilkan 5 baris pertama dengan function head.
df.head()

TransactionAmount PreviousTransactionDate  TransactionType  Location  \
0         27036.8565     2023-04-11 16:29:14                1        36   
1        721948.3840     2023-06-27 16:44:19                1        15   
2        242331.8265     2023-07-10 18:16:08                1        23   
3        354028.0850     2023-05-05 16:32:11                1        33   
4        176822.2875     2023-04-03 17:15:01                1        28   

   Channel  CustomerAge  CustomerOccupation  TransactionDuration  \
0        0       4358.0                   0              23500.0   
1        0       4234.0                   0              40900.0   
2        2       1196.0                   3              16250.0   
3        2       1630.0                   3               7260.0   
4        0       1134.0                   3              49890.0   

   LoginAttempts  AccountBalance     TransactionDate  AgeGroup  AmountGroup  \
0            5.0    7.605312e+07  2024-11-04 8:08:08         1            0   
1            5.0    2.046878e+08  2024-11-04 8:09:35         1            0   
2            5.0    1.669701e+07  2024-11-04 8:07:04         2            0   
3            5.0    1.274798e+08  2024-11-04 8:09:06         2            0   
4            5.0    1.162895e+07  2024-11-04 8:06:36         3            0   

   Cluster  
0        3  
1        0  
2        1  
3        3  
4        1

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [4]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
X = df.drop(columns=["Cluster"])
y = df["Cluster"]

X = X.drop(columns=["TransactionDate", "PreviousTransactionDate"], errors="ignore")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Ukuran X_train:", X_train.shape)
print("Ukuran X_test :", X_test.shape)
print("Ukuran y_train:", y_train.shape)
print("Ukuran y_test :", y_test.shape)

Ukuran X_train: (1382, 11)
Ukuran X_test : (346, 11)
Ukuran y_train: (1382,)
Ukuran y_test : (346,)


# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [5]:
# Buatlah model klasifikasi menggunakan Decision Tree
dt = DecisionTreeClassifier(
    criterion="gini",
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)
dt.fit(X_train, y_train)

# === 4) Evaluasi ===
y_pred = dt.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc:.4f}\n")
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0000

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        89
           1       1.00      1.00      1.00        89
           2       1.00      1.00      1.00        86
           3       1.00      1.00      1.00        82

    accuracy                           1.00       346
   macro avg       1.00      1.00      1.00       346
weighted avg       1.00      1.00      1.00       346

Confusion Matrix:
 [[89  0  0  0]
 [ 0 89  0  0]
 [ 0  0 86  0]
 [ 0  0  0 82]]


In [6]:
# Menyimpan Model
# import joblib
# joblib.dump(model, 'decision_tree_model.h5')
joblib.dump(dt, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [7]:
svm = SVC(
    kernel="rbf",
    C=1.0,
    gamma="scale",
    random_state=42
)
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)
acc_svm = accuracy_score(y_test, y_pred_svm)

In [8]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
print(f"SVM Accuracy: {acc_svm:.4f}\n")
print("SVM Classification Report:\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM Accuracy: 0.2428

SVM Classification Report:
               precision    recall  f1-score   support

           0       0.29      0.33      0.31        89
           1       0.24      0.39      0.30        89
           2       0.20      0.23      0.22        86
           3       0.00      0.00      0.00        82

    accuracy                           0.24       346
   macro avg       0.18      0.24      0.20       346
weighted avg       0.19      0.24      0.21       346

Confusion Matrix:
 [[29 38 22  0]
 [23 35 31  0]
 [25 41 20  0]
 [24 32 26  0]]


c:\Users\Rahfi\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Rahfi\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Rahfi\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [9]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')
joblib.dump(svm, 'explore_svm_classification.h5')

['explore_svm_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [10]:
# === Pipeline: scaling + SVM ===
svm_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(random_state=42))
])

# ruang pencarian hyperparameter (hanya utk SVM, bukan scaler)
param_space = {
    "svm__C": Real(1e-3, 1e3, prior="log-uniform"),
    "svm__gamma": Real(1e-4, 1e1, prior="log-uniform"),
    "svm__kernel": Categorical(["linear", "rbf", "poly"])
}

# stratified k-fold
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# bayesian search
opt = BayesSearchCV(
    estimator=svm_pipe,
    search_spaces=param_space,
    n_iter=30,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# training + tuning
opt.fit(X_train, y_train)

# hasil terbaik
print("Best Params:", opt.best_params_)
print("Best CV Score:", opt.best_score_)

# latih ulang dengan best estimator
best_svm = opt.best_estimator_
y_pred_best_svm = best_svm.predict(X_test)


Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fits
Fitting 5 folds for each of 1 candidates, totalling 5 fi

In [11]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
print(f"\nTuned SVM Accuracy: {accuracy_score(y_test, y_pred_best_svm):.4f}\n")
print("Classification Report:\n", classification_report(y_test, y_pred_best_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_best_svm))


Tuned SVM Accuracy: 1.0000

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        89
           1       1.00      1.00      1.00        89
           2       1.00      1.00      1.00        86
           3       1.00      1.00      1.00        82

    accuracy                           1.00       346
   macro avg       1.00      1.00      1.00       346
weighted avg       1.00      1.00      1.00       346

Confusion Matrix:
 [[89  0  0  0]
 [ 0 89  0  0]
 [ 0  0 86  0]
 [ 0  0  0 82]]


In [12]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(__, 'tuning_classification.h5')
joblib.dump(best_svm, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code